### ISSUE TITLE
What is the difference between crv and cv?

### ISSUE THREAD

**Issue by SherryLeunglxy** [vlad-yeghiazaryan/QADF#1]
Hello, Sir! 
In your quantileADF.py code, there is a crv in the row144 and a cv in row216. They look like same, so I want to ask what is the difference between crv and cv? Moreover, are they both critical values for the estimated nuisance parameter? And is there the critical value for QURadf in this package?
Hope to your reply! Thank you very much!

**Comment by vlad-yeghiazaryan** [comment]
There is no difference between the two. As you can see, I've omitted crv from the output, so it doesn't affect anything. At the same time, I forgot to remove the initial definition. Thank you for pointing this out. I'll update the code shortly.

As for the second question, we use the nuisance parameter δ² to obtain the critical values for QURadf (tₙ(τ)). We do this by mapping δ² to the table of covariate-ADF (CADF) test critical values provided by Hansen et al. (1995). Please also note that it is a one-tailed test. 
Since the QADF test is nonparametric you are also free to use the bootstrapping procedure described in the usage section of this repository. Especially if the goal is to obtain critical values for the QKS statistic.

**Comment by vlad-yeghiazaryan** [comment]
Done. I've also added a small background code that tracks convergence failures when using the `fitForQuantiles` function.

3252c3cdd2c55e05c151d204827b6a012b313716

**Comment by SherryLeunglxy** [comment]
> As for the second question, we use the nuisance parameter δ² to obtain the critical values for QURadf (tₙ(τ)). We do this by mapping δ² to the table of covariate-ADF (CADF) test critical values provided by Hansen et al. (1995). Please also note that it is a one-tailed test.

Thanks for your quick reply! So do you mean the cv in row220 is the critical value for QURadf(tₙ(τ)) and the output CV10%, CV5% and CV1% is also the critical value of (tₙ(τ))?

Look forward to your reply. Thank you so much!

**Comment by vlad-yeghiazaryan** [comment]
Yes, the variable cv encompasses the vector of critical values for tₙ(τ) at 10%, 5%, and 1% confidence intervals, respectively. This data is outputted in the results in the form of 3 individual variables (CV10%, CV5%, and CV1%).

**Comment by vlad-yeghiazaryan** [comment]
For more details, please take a look at the [original paper](https://doi.org/10.1198/016214504000001114), sections 3.1 and 3.4.
